[build]
builder = "NIXPACKS"

[deploy]
startCommand = "bash start.sh"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
healthcheckPath = "/admin"
healthcheckTimeout = 100
healthcheckInterval = 30

[env]
PYTHON_VERSION = "3.11"
