[build]
builder = "NIXPACKS"

[deploy]
startCommand = "python manage.py migrate --noinput && gunicorn stationery_tracker.production_settings:application --bind 0.0.0.0:$PORT --workers 1 --timeout 300 --access-logfile - --error-logfile - --log-level critical --capture-output"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
PYTHON_VERSION = "3.11"
DJANGO_SETTINGS_MODULE = "stationery_tracker.production_settings"
